### ISSUE TITLE
Create a SBOL 2 example of CombinatorialDerivation using pySBOL2

### ISSUE THREAD

**Issue by PrashantVaidyanathan** [SynBioDex/SBOL-Notebooks#10]

**Comment by fxbuson** [comment]
I'm having a go at this and currently am getting a validation error I don't think I should be getting. Am I doing something wrong?

Here's the code and error:

```python
import sbol2

doc2 = sbol2.Document()

# Add a Definition with a Component
gene = sbol2.ComponentDefinition("Example_Gene")
pro = sbol2.ComponentDefinition("Base_Promoter")
for obj in [gene, pro]:
    doc2.add(obj)

g_pro = sbol2.Component("BasePro_instance")
g_pro.definition = pro.identity
gene.components = [g_pro]

# Create variants of the Component
pro_variants = [sbol2.ComponentDefinition("Promoter_Variant_"+str(num + 1)) for num in range(3)]
for obj in pro_variants:
    doc2.add(obj)

# Make CombinatorialDerivation with the variants
comb = sbol2.CombinatorialDerivation(uri = "Promoter_Exchange")
comb.template = gene.identity

varying_pro = sbol2.VariableComponent(uri = "Possible_Promoters")
varying_pro.variable = g_pro
varying_pro.variants = [obj.identity for obj in pro_variants]
varying_pro.operator = "http://sbols.org/v2#one"

comb.variableComponents = [varying_pro]

doc2.add(comb)

print(doc2.validate())
```


> Invalid. sbol-12904: Strong Validation Error: The template property of a CombinatorialDerivation is REQUIRED and MUST contain a URI. Reference: SBOL Version 2.3.0 Section 7.11 on page 47 : http://examples.org/CombinatorialDerivation/Promoter_Exchange/1  Validation failed.

**Comment by jakebeal** [comment]
Looking in https://github.com/SynBioDex/pySBOL2/blob/master/sbol2/combinatorialderivation.py , it looks like pySBOL2 might have internally called that variable `masterTemplate` instead

It also looks like you are missing the `strategy`

**Comment by fxbuson** [comment]
Ah, I should've checked! Thank you, now everything validates and I think it looks correct.
